version: '2'
services:
  web:
    image: howie6879/owllook
    command: pipenv run gunicorn -c /owllook/config/dev_gunicorn.py --worker-class sanic.worker.GunicornWorker owllook.server:app
    ports:
      - "8001:8001"
#    volumes:
#      - .:/owllook
  mongo:
    image: mongo:3.2.11
    volumes:
      - /data/db/mongo
    ports:
      - "27017:27017"
  
  redis:
    image: redis
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"
